WIP - Update bootstrap template to match today's reality
get-bridge/truss-cli pull request #95
Opened 2022-11-18 22:09 UTC by psi

This definitely needs docs and likely some tweaking and cleanup, but this is the bulk of the work...

Major changes from the previous version are:
* Switch from per-deploy target directories to using Terraform workspaces
* Use the newest version of Terraform and the kustomization provider, which can now be downloaded and installed from the registry
* Get rid of Istio-specific resources
* Configure an Ingress with TLS and DNS
* Includes examples of using secrets, ready to push

Once we're happy with this, I'll just make it the new `default` template, but I put it in a separate directory to keep the PR clean for review.

2022-11-18 22:09 UTC, psi commented on bootstrap-templates/default-20021118/common/providers.tf
> +  region              = "us-east-2"
This will need to be parameterized per-region

2022-11-18 22:10 UTC, psi commented
This should probably also either include or at least have docs about adding a promotion pipeline.

2022-11-18 22:12 UTC, psi commented
A note for newer folks: yes, we kind of reinvented helm here. 🤷‍♂️

2022-11-18 22:42 UTC, psi commented on bootstrap-templates/default-20021118/common/providers.tf
> +  region              = "us-east-2"
actually i lied. this one is fine. if i add an aws provider to `deploy/providers.tf`, it will need to be parameterized.

2022-11-22 17:27 UTC, adamgoose requested changes
Just a couple things, otherwise looks like Terraform to me! ;)

2022-11-22 17:27 UTC, adamgoose commented on bootstrap-templates/default-20021118/.truss-manifest.yaml
> +name: default-2022-from-scratch
Your directory is misnamed.

2022-11-22 17:27 UTC, adamgoose commented on bootstrap-templates/default-20021118/deploy/kustomize.tf
> +data "kustomization_overlay" "{{ .Params.name }}" {
:sobeautiful:

2022-11-22 17:27 UTC, adamgoose commented on bootstrap-templates/default-20021118/deploy/kustomize/horizontalpodautoscaler-{{ .Params.role }}
> +apiVersion: autoscaling/v2beta2
File missing `.yaml` extension

2022-11-22 17:27 UTC, adamgoose commented on bootstrap-templates/default-20021118/deploy/kustomize/kustomization.yaml
> +  - horizontalpodautoscaler-{{ .Params.role }}
Missing `.yaml` here

2022-11-22 21:18 UTC, adamgoose approved these changes

2022-12-05 22:11 UTC, adamgoose approved these changes
Looks great!

2022-12-05 23:37 UTC, merged